#!/bin/bash

AWS_ACCESS_KEY_ID="AKIAYR6QZ6LJHTREWHNV" AWS_SECRET_ACCESS_KEY="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" S3_SECRET_KEY="+5PQ2SvObxRrgjt8xBsrntmoj/Pc2aCYJqcTQLCg" PORT=4000 HOST="0.0.0.0" SANDBOX_CONFIG="sandbox.json" cargo run --release
